project_id = "huvuogyvgeoqiqltbgcw"
[functions.wallet-pay]
enabled = true
verify_jwt = false
import_map = "./functions/wallet-pay/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/wallet-pay/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/wallet-pay/*.html" ]

[functions.crm-manage]
enabled = true
verify_jwt = false
import_map = "./functions/crm-manage/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crm-manage/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crm-manage/*.html" ]

[functions.debug-db]
enabled = true
verify_jwt = false
import_map = "./functions/debug-db/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/debug-db/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/debug-db/*.html" ]

[functions.send-campaign-sms]
enabled = true
verify_jwt = false
import_map = "./functions/send-campaign-sms/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-campaign-sms/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-campaign-sms/*.html" ]

[functions.paystack-process]
enabled = true
verify_jwt = false
entrypoint = "./functions/paystack-process/index.ts"

[functions.paystack-reconcile]
enabled = true
verify_jwt = false
entrypoint = "./functions/paystack-reconcile/index.ts"

[functions.auth-sms-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/auth-sms-webhook/index.ts"

[functions.admin-provider-action]
enabled = true
verify_jwt = false
entrypoint = "./functions/admin-provider-action/index.ts"

[functions.payment-lookup]
enabled = true
verify_jwt = false
entrypoint = "./functions/payment-lookup/index.ts"

[functions.swiftdata-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/swiftdata-webhook/index.ts"
